apiVersion: skaffold/v2beta15
kind: Config
metadata:
  name: hello-12fa
build:
  artifacts:
  - image: hello-12fa
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - deployments/*
