apiVersion: skaffold/v2beta15
kind: Config
metadata:
  name: fastapi-app
build:
  artifacts:
  - image: fastapi-app
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - deployments/*
